### ISSUE TITLE
Network request failed] Working Yarn and Expo?

### ISSUE THREAD

**Issue by GollyJer** [BulletTrainHQ/react-native-performance-monitor#3]
Hi! This tool looks to be super helpful! Thanks for putting it together.
Normally, when instructions call for `npx` commands, yarn just works.
Is npx required? 

We're also using Expo. Is it possible this won't work with an Expo project?

I'm 99% sure yarn worked because the package is installed and I'm able to access the server at http://127.0.0.1:8125/.

This is the error when attaching `withPerformanceMonitor` to a screen.
```
[Unhandled promise rejection: TypeError: Network request failed]
- node_modules\whatwg-fetch\dist\fetch.umd.js:473:29 in xhr.onerror
- node_modules\event-target-shim\dist\event-target-shim.js:818:39 in EventTarget.prototype.dispatchEvent
- node_modules\react-native\Libraries\Network\XMLHttpRequest.js:574:29 in setReadyState
- node_modules\react-native\Libraries\Network\XMLHttpRequest.js:388:25 in __didCompleteResponse
- node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js:190:12 in emit
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:436:47 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:26 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue
```

I can provide any other info you need. Thanks!

**Comment by kyle-ssg** [comment]
Npx commands simply scan node modules for binaries, the alternative would be to install the module globally and run it via npm run.

Is this on an Android simulator by any chance? It could be that you can’t access localhost via the simulator

**Comment by GollyJer** [comment]
OK, I see the issue. Not sure why it didn't jump out at me right away.
I'm running a physical device.  Once I updated the wrapper to use the ip address it's all good!
 
```javascript
export default withPerformanceMonitor(AwesomeChat, 'AwesomeChat', '192.168.1.10');
```

Thanks! 🎉

**Comment by kyle-ssg** [comment]
Ah perfect! Have you found it useful? I'm super curious to see how people find it. Found it quite satisfying to use and play around with.

**Comment by GollyJer** [comment]
I'm loving it. I haven't used it for code optimization yet but it's been fun comparing physical devices. For example... here's the render time of a chat screen with 12 bubble messages. It renders three separate times as cache hits and query results roll in. The Pixel feels instant and the iPhone feels slow. This shows why.

<img width="800" alt="2020-03-20_12h48_34" src="https://user-images.githubusercontent.com/689204/77201169-46ea5100-6aa9-11ea-9416-16b726e6998b.png">

I'm already thinking of UX requests. 😃 
Is this something you put out there for others to take and run with or are you looking run it as a managed open source project?

**Comment by kyle-ssg** [comment]
Awesome, really glad to see this!

That's a really good question! I guess that totally depends on the requests / where this goes really, I've only really just put it out there.

I've got a fair amount of ongoing projects with Bullet Train, but since I'm going to end up using this to help people out with mobile projects I will definitely do a lot of maintenance myself, but help is of course always welcome.

Yeah let me know if you have any suggestions based on experience, I might make a public board if this gets enough activity.

**Comment by GollyJer** [comment]
On first blush here are the things I think would be useful...

- Show the average and total duration for each test.
- Distinguish between mount vs update in the chart.
- A "Clear Results" button that doesn't clear out the test names.
- Ability to specify which test will run. Like, whichever test name is active will be the one that runs.

I'd love to help but like you I have a small business to run. If I do find time this project will definitely be towards the top of my list.
(Bullet Train looks awesome by the way). I could see us using it in the future.

**Comment by kyle-ssg** [comment]
@GollyJer Cheers for the feedback, I'll add these in an issue just so that I can track it, all good suggestions!

PS thanks RE Bullet Train, we're definitely really happy with how it's grown!
