### ISSUE TITLE
Suggestion: add hoisting of non-react statics

### ISSUE THREAD

**Issue by bitcrumb** [BulletTrainHQ/react-native-performance-monitor#4]
Hi, when applying the `withPerformanceMonitor` HOC to a component with statics on it (e.g. for `react-native-navigation`), the statics don't get hoisted.  And thus, the app behaves unexpectedly since these statics can not be found (they effectively still are attached to the now *child* component). An easy fix would be to use the HOC from `hoist-non-react-statics` which takes care of this for you :)

It is just a matter of exporting the `withPerformanceMonitor` differently:
` return hoistNonReactStatics(HOC, WrappedComponent);`

**Comment by kyle-ssg** [comment]
Hey @bitcrumb, cheers for pointing this out! I've added hoist-non-react-statics as mentioned, it's published under 1.1.0, I'll leave this open for now. If you get the chance, let me know if this is working for you and I can close the issue.

**Comment by bitcrumb** [comment]
I can confirm that it is fixed. Thanks for your swift reply! 💯

**Comment by kyle-ssg** [comment]
Caught me perfectly working day haha! Glad it's all resolved.
