### ISSUE TITLE
UX Suggestions / nice to haves

### ISSUE THREAD

**Issue by kyle-ssg** [BulletTrainHQ/react-native-performance-monitor#5]
- Show the average and total duration for each test.
- Distinguish between mount vs update in the chart.
- A "Clear Results" button that doesn't clear out the test names.
- Ability to specify which test will run. Like, whichever test name is active/clicked/checked will be the one that runs.

**Comment by aaronfg** [comment]
Some way to export the before/after results for each test would be nice too.

Thinking about this as a tangible thing to show bosses: "Refactoring this component gave us an x second performance benefit".

The suits like to see numbers.

**Comment by kyle-ssg** [comment]
Ah thats an awesome idea @aaronfg, can totally imagine this haha

**Comment by kyle-ssg** [comment]
Alright, that sounds like a good start then. I'll take a look at it this evening when I'm done with work!

**Comment by aaronfg** [comment]
> Edit: This is live in v 1.2.1 @aaronfg

Nice! Been super busy with work and quarantine craziness so haven't had a chance to get back to testing this. The image looks great though!
